Iter9
olkonon/shortener pull request #9
Opened 2023-10-29 11:21 UTC by olkonon

2023-10-30 05:27 UTC, edylcrm requested changes

2023-10-30 05:27 UTC, edylcrm commented on internal/app/common/gen_random_string_test.go
> +func init() {
[LINT] Лучше избегать функций init()

2023-10-30 05:27 UTC, edylcrm commented on autotest-local.sh
>  ### Workflow statictest.yml ###
**[BLOCKER]** -  Проблема, не решив которую принять работу нельзя
**[LINT]** - Заменичение, опционально к выполнению
**[FYI]** - просто ремарка

2023-10-30 05:27 UTC, edylcrm commented on internal/app/handler/handler.go
> +func getBodyGzip(r *http.Request) ([]byte, error) {
[LINT] вообще это лучше сделать в виде middleware, чтобы при каждом добавлении нового endpoint не нужно было думать о gzip

2023-10-30 05:27 UTC, edylcrm commented on internal/app/handler/log_handler.go
> +		bodySize:   0,
[LINT] по умолчанию эти значения и так будут 0, тут можно явно не писать

2023-10-30 05:27 UTC, edylcrm commented on internal/app/storage/file/file.go
> +	for IDIsExists {
[LINT] вообще можно взять какой-нибудь алгоритм sha1 как делает git для нумерации коммитов и использовать его для генерации сокращенной ссылки. С таким подходом можно будет использовать одну map вместо двух потому что генерация строки для короткой ссылки всегда будет одинакова для одной и той же ссылки

2023-10-30 05:27 UTC, edylcrm commented on internal/app/storage/file/file.go
> +	f, err := os.OpenFile(fs.filePath, os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0600)
[BLOCKER] не стоит каждый раз открывать файл при записи в него каких-то данных. Лучше открыть его один раз при инициализации структуры. Так же писать каждый раз в файл при добавлении новой ссылки дорогая операция. Лучше записывать данные в файл batch запросом.

2023-10-30 05:50 UTC, olkonon commented on internal/app/storage/file/file.go
> +	f, err := os.OpenFile(fs.filePath, os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0600)
На самом деле конкретно в этом случае, это не так. Так как, здесь паттерн нагрузки мало записей много чтений (а чтения идут из кэша), то тем, что открытие файла долгая операция можно пренебречь. Плюс при постоянно открытом файле вырастает вероятность повреждения или потери данных, например если придет ООМ.

2023-10-30 06:10 UTC, edylcrm commented on internal/app/storage/file/file.go
> +	f, err := os.OpenFile(fs.filePath, os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0600)
Почему должен прийти ООМ? Открытие файла это просто получение файлового дескриптора

2023-10-30 06:11 UTC, edylcrm commented on internal/app/storage/file/file.go
> +	f, err := os.OpenFile(fs.filePath, os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0600)
В текущий реализации как раз получение этого файлового дескриптора происходит каждый раз, хотя можно сделать это один раз

2023-10-30 18:04 UTC, olkonon commented on internal/app/storage/file/file.go
> +	f, err := os.OpenFile(fs.filePath, os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0600)
Я говорю про реальный сервис, ООМ просто пример того, что может произойти  по  независящим от сервиса причинам. Пропало питание в ЦОД например, ну или заддосили запросами на чтение (как раз тогда система пристрелит сервис по ООМ, т.к. на каждую сессию будет выделяться память и если она не бесконечно ее рано или поздно не хватит)

2023-10-30 18:37 UTC, olkonon commented on internal/app/common/gen_random_string_test.go
> +func init() {
Согласен, но не знаю больше ни одного способа отключить логирование для теста без дублирования кода в каждом тесте, если он есть, то был бы рад о нем узнать.

2023-10-30 18:50 UTC, olkonon commented on internal/app/handler/log_handler.go
> +		bodySize:   0,
Все же поскольку они пишутся в лог, лучше сделать их поведение максимально детерминированным, чтобы потоком не гадать, почему в логе код ответ сервиса 42). Например если возникнет баг в языке, где инициализация будет отдавать содержимое ячейки памяти, или просто разработчики языка решат поменять дефолтные значения. Оно конечно маловероятно, но имхо стоит 2-х строчек кода в IDE

2023-10-30 19:29 UTC, olkonon commented on internal/app/handler/handler.go
> +func getBodyGzip(r *http.Request) ([]byte, error) {
Переделал на middleware, но получилось достаточно уродливо

2023-11-01 08:58 UTC, edylcrm commented on internal/app/common/gen_random_string_test.go
> +func init() {
Дублирование кода это не страшно :) Страшно когда прод падает и не понятно почему. А там очередность вызовов функций init() поехали

2023-11-01 09:00 UTC, edylcrm commented on internal/app/storage/file/file.go
> +	f, err := os.OpenFile(fs.filePath, os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0600)
Не понимаю, при чем тут открытие дескриптора один раз вместо каждого запроса на чтение, может привести к проблемам которые ты описать выше :(

2023-11-01 09:03 UTC, edylcrm commented on internal/app/handler/log_handler.go
> +		bodySize:   0,
Это прям совсем какой-то нереальный кейс :) Это заложено в архитектуру языка, поменять уже не получится, даже если сильно захотеть

2023-11-01 09:05 UTC, edylcrm approved these changes

2023-11-01 10:53 UTC, olkonon commented on internal/app/storage/file/file.go
> +	f, err := os.OpenFile(fs.filePath, os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0600)
Сейчас речь идет исключително об ОС linux и ФС ext4. Это старая проблема, что вызов syscall fsync (в который и разварачивается file.sync() ) не вызывает синка файлового кэша на диск, и поскольку файл всегда открыт, то его состояние в программе и на диске отличается. При вызове close() же происходит сброс файлового кэша на диск(если дескриптор не используется никаким другим процессом). Соответсвенно когда резко пропадет питание данные оказываются невалидными. Это кстати вполне себе реальный кейс из практики. Собственно поэтому я и предпочитаю не держать файлы открытыми если,в этом нет особой необходимости(например постоянная запись запись). Собственно поэтому Enterprise БД(типа oracle,db2) и используют directio вместо стандартных средств предоставляемых ОС.

2023-11-01 10:54 UTC, merged